### ISSUE TITLE
Using latex with curly braces results in improper cloze deletion cards

### ISSUE THREAD

**Issue by Vishnu-Karthik** [l3kn/org-fc#113]
Working example:
```
Some function {{ \(f: N \to R\) }}
Let {{ \(a_n\) }} be a sequence
```

Not working example:
```
Some function {{ \(f:\mathbb{N} \to \mathbb{R}\) }}
Let {{ \( \{ a_n \} \) }} be a sequence
```

The improper cards look like this:
```
* Let {{ \( \{ a_n \} \) }} be a sequence :fc: 
:PROPERTIES:
:FC_CREATED: 2023-09-18T11:50:14Z
:FC_TYPE:  cloze
:ID:       f1c05190-8e11-43d2-b8c3-c7e9bffbb526
:FC_CLOZE_MAX: -1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due |
|----------+------+-----+----------+-----|
:END:
```

**Comment by l3kn** [comment]
Because the cloze-hole syntax uses curly braces, it's hard to detect where a hole begins or ends when it is combined with latex. If you're fine with using the alternative `$f:\mathbb{N} \to \mathbb{R}$` latex syntax, there's a special case in the regex for that and so far I haven't run into issues with it.

I'll take a look at the regex to see if a similar special case is possible for `\(....\)` inline-latex.

**Comment by Vishnu-Karthik** [comment]
Yeah `$...$` works. I'll switch to using that. Thanks :)
