### ISSUE TITLE
Quick question regarding normal card format

### ISSUE THREAD

**Issue by Vishnu-Karthik** [l3kn/org-fc#120]
Hi,

I notice that the basic card format in the demo is:

```
* Front
Front
** Back
Back

```
But while using it, I get an ID mismatch if I'm on the back portion and the back heading doesn't open up when I click show, so the format below works better.
```
* Front
Back
```

Does it make much of a difference? Additionally, when using the first format, the back heading does not open up automatically. Is there a way to get that to happen?  I'd prefer to use the second format if it doesn't affect the program in anyway.

Thanks

**Comment by l3kn** [comment]
Org-fc currently expects the cursor (point) to be at the heading or within the contents of the flashcard during review.
When using the first format and with the cursor at the “back heading”, the card will not be flipped because org-fc
compares heading IDs to make sure it won't update the wrong card during review.

Besides the second format being more compact and different parts of the heading/card being shown before and after flipping it, there's no difference between both formats.

Usually, the cursor should be placed in the correct stop by the review, did you move the cursor before trying to flip the card?

**Comment by Vishnu-Karthik** [comment]
Yes, I had my cursor in the back heading. Thank you for the clarification.

**Comment by l3kn** [comment]
If you regularly flip cards after moving around in the heading that is reviewed, we could add some code that tries to moves up the hierarchy of headings until it finds one belonging to a flashcard.

**Comment by Vishnu-Karthik** [comment]
Yes, I move it around a fair bit before flipping but I don't think there's a need to go through the trouble of adding code. I'll just use the compact format which does exactly what I want.
