### ISSUE TITLE
Personal contexts stopped working

### ISSUE THREAD

**Issue by gab-dev** [l3kn/org-fc#124]
I've just reinstalled emacs:
`GNU Emacs 29.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2024-03-13`
and I've also got the last version of org-fc.
The problem is that whenever I try to review cards using personal context, I receive this error.
`oref: Wrong type argument: (or eieio-object cl-structure-object oclosure), (:id "328aa000-9ed3-4ec2-b779-67c059cfb29b"...`

No probelm if I start a review using 'all' or 'buffer'.

Everything was working before.

**Comment by l3kn** [comment]
Are you using org-fc without the cache mode?
I was looking at the code yesterday and found that I had missed updating the filter-code.

There are some big internal changes I'd like to implement with the next version
but I've now pushed some parts of that and the fix for your issue.
Please let me know if this fixes your issue. 

One thing to watch out for: when creating a new card, you'll now be prompted for the spacing algorithm you'll have to select `sm2`.
There will probably be some way to skip this selection and set a default algorithm but I haven't decided on an implementation yet.

**Comment by gab-dev** [comment]
Thanks for your immediate support but I can't see your push. Am I missing something?

**Comment by l3kn** [comment]
The relevant change is part of https://github.com/l3kn/org-fc/commit/cf70a398402b00be1665b4f2e4692ce3ae706bfe which should now be on the main branch.

It should show up as a few days old because that's when I made the commit on my local copy.

**Comment by gab-dev** [comment]
Now I'm getting this
```if: Org-fc shell error: gawk: fatal: cannot open source file `/home/gabriele/.emacs.d/packages/org-fc/awk/stats_reviews.awk' for reading: No such file or directory```

**Comment by l3kn** [comment]
Sorry for the inconvenience, can you try again with the most recent version of org-fc?

I've tested it in a new Emacs setup and there it works as expected.

**Comment by gab-dev** [comment]
Everything works fine now.
Thank you
