### ISSUE TITLE
`remove-if-not` should have `cl-` prefix

### ISSUE THREAD

**Issue by Tubo** [l3kn/org-fc#29]
Hi, I just installed the package and the demo was broken due to invalid symbol `remove-if-not`. I gathered you forgot to add the `cl-` prefix.

https://github.com/l3kn/org-fc/blob/f8ae5004fe4f117933fc7a8a59d7cde0510f054a/org-fc.el#L1380

PS: it would be nice to be able to customize keyboard shortcuts

**Comment by l3kn** [comment]
Fixed with the current commit.
Usually I have a script that checks for things like this but that's broken at the moment,
I hope I didn't miss any other `cl-` prefixes.

Customizable keyboard shortcuts for the review would be nice,
with the current implementation you'd need to redefine the two hydras.
(`org-fc-review-flip-hydra` and `org-fc-review-rate-hydra`)

Ideally, there would be minor modes for flipping / rating card
(like https://github.com/abo-abo/pamparam).
I have not found a good way to make this work with evil-mode yet.

https://gitlab.com/phillord/org-drill uses `read-key` during review,
with a bunch of `defvar`s for each key.

I'll see if I can get one of the approaches to work

**Comment by l3kn** [comment]
Hi @Tubo,

I've pushed a branch with new implementation of the review loop using two minor modes,
this way keyboard shortcuts can be customized using `define-key`.

I still need to write some documentation for it and make sure the modes are reset correcty in all scenarios, but I've been using this for a few days without any problems.

If you'd like to help with testing, you can check out the `mode-based-review` branch
(https://github.com/l3kn/org-fc/tree/mode-based-review).

**Comment by l3kn** [comment]
Mode based review has been merged.
