### ISSUE TITLE
org-fc hydra like bar in minor mode implementation

### ISSUE THREAD

**Issue by natask** [l3kn/org-fc#32]
are there plans to include a hydra like bar in the bottom for the minor mode implementation? 
What I liked with the hydra implementation is that I can see the keys I need to press on the bottom.
Thanks

**Comment by Tubo** [comment]
There should be one by default. Are you not seeing the bottom hydra bar, like below?

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7521921/85849148-89d16880-b7fe-11ea-91f2-fc1a348b0693.png">

**Comment by l3kn** [comment]
@natask I'll see if I can come up with something.
The easiest solution would be to show a `message` listing all keys each time one of the modes is entered.
One problem with that is that the minor-mode keymaps don't include labels like "Flip" and "Quit",
only the function names (`org-fc-review-flip` and `org-fc-review-quit`).

How do you like the new header-line showing the review progress?

@Tubo With a recent commit the two hydras have been replaced by two minor modes
and the status line (cards remaining / percent right) has been moved to the header-line of the buffer.

**Comment by l3kn** [comment]
A quick workaround might look like this:

``` emacs-lisp
(defun org-fc-review-flip-mode-hint ()
  (message "[RET] Flip [s]uspend [q]uit"))

(defun org-fc-review-rate-mode-hint ()
  (message "[a]gain [h]ard [g]ood [e]asy [s]uspend [q]uit"))

(add-hook 'org-fc-review-flip-mode-hook #'org-fc-review-flip-mode-hint)
(add-hook 'org-fc-review-rate-mode-hook #'org-fc-review-rate-mode-hint)
```

![2020-06-26_hints](https://user-images.githubusercontent.com/2060269/85856902-1a855580-b7b9-11ea-8c0a-4ee43caa1bfe.png)

There's an option to define keymap entries with an additional string,
however I've not found any information on what this is used for.

``` emacs-lisp
(setq org-fc-review-flip-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "RET") '("Flip" . org-fc-review-flip))
    (define-key map (kbd "q") '("Quit" . org-fc-review-quit))
    (define-key map (kbd "s") '("Suspend". org-fc-review-suspend-card))
    map))
```

These strings could be used for the labels in the hint message,
but that would require some logic for formatting `(kbd "RET")` as `RET` instead of `^M`.

**Comment by natask** [comment]
the workaround you recommend works fine for my current workflow. I would imagine that the second approach works well for letters. therefore Even without support for formatting in the beginning, it would clean to integrate keymap configurations with bottom bar messages and display most of them as expected.

**Comment by l3kn** [comment]
I've added a `contrib/` directory for extensions like this
that might be more experimental / unstable than "core" org-fc.

You can enable keymap-hints with `(require 'org-fc-keymap-hint)`.

**Comment by l3kn** [comment]
One thing I dislike about the current implementation is that there are two ways keys are shown:

1. At the bottom of the buffer when flipping / rating cards
2. in the header line when editing cards

Removing the rating stats from the header line, the flip / rate keys could be shown there, too.
 
Because the header line can't contain linebreaks (as far as I know)
this would not scale well for larger keymaps, but at least it would be consistent.

Any opinions on this?

**Comment by l3kn** [comment]
Closing, moved to https://todo.sr.ht/~l3kn/org-fc/6
