### ISSUE TITLE
Org-fc shell error

### ISSUE THREAD

**Issue by xyank-github** [l3kn/org-fc#42]
For a file with this content:
```
* Test :fc:
New
```

I get this error:
```
if: org-fc shell error: [REDACTED DATE]
(
)
```

I'd like a hint as to what is going on

**Comment by xyank-github** [comment]
Right, forgive me. I read the code and realized that it is directly piping the output from the "shell", and my fish shell, when initialized, always prints the date in the first line.

I've fixed the issue by commenting out that line in my fish config, but I _do_ consider this an issue, so I will leave this up here.

**Comment by l3kn** [comment]
I think this can be fixed by wrapping all calls to `shell-command-to-string` in a `(let ((shell-file-name "/bin/bash")) ...)`,
although it might break on systems where bash is not installed (at that location).

The shell commands could also go into separate files, in that case I'd need to figure out how to pass the directories and awk variables.

Do you have a better idea how to fix this?

**Comment by xyank-github** [comment]
Can we use `sh`? I doubt `sh` can be customized like `bash` and `fish`. Also, `sh` is almost always in `/bin/sh`.

Honestly, this is _still_ a workaround. I guess this is either an `emacs` or a `fish` issue that causes emacs to parse output run when you initiate a shell instead of just piping an input and getting that output.

**Comment by l3kn** [comment]
Closing, moved to https://todo.sr.ht/~l3kn/org-fc/3
