### ISSUE TITLE
Pronunciation learning with org-fc-audio

### ISSUE THREAD

**Issue by souew** [l3kn/org-fc#52]
Why _org-fc-audio-set-after_ only works for text input cards, let's say I want **배우기** to be the front, then I recall pronunciation, and the back should be the audio reference, I don't need to type anything to compare.
There are other cards like that, with general knowledge (regular front/back cards), but with English pronunciation on the back, for difficult to pronounce terms and non English speaking learner. It utilizes two sensory systems, visual and auditory.
Will it be difficult to implement?

**Comment by l3kn** [comment]
That's due to a design flaw in `org-fc-audio`.

Internally the "before" and "after" apply to "before setting up the card"
and "after setting up the card", a distinction that only makes sense for text-input cards
because the text prompt is shown during the card setup.

I think it would make more sense to change it so the "after" audio file is played after the card is either flipped (for normal cards)
or text input has been entered (for text-input cards).

It's not hard to fix but I need to spend some time thinking about how to best implement it.

**Comment by l3kn** [comment]
I couldn't find a way to make org-fc-audio work with double or cloze cards but I've type of audio file that plays after a card is flipped.
It can be set with `org-fc-audio-set-after-flip`. `org-fc-audio-set-after` has been renamed to `org-fc-audio-set-after-setup`.

If you have already used `org-fc-audio-set-after` for files that should play after a normal card is flipped,
you'll have to rename the properties in the org file.
