### ISSUE TITLE
condition-case: Invalid function: org-fc-with-point-at-back-heading Mark set

### ISSUE THREAD

**Issue by jaaved** [l3kn/org-fc#62]
Getting the error: `condition-case: Invalid function: org-fc-with-point-at-back-heading Mark set ` when I flip the card or hit RET.

Emacs 28.0.50

**Comment by l3kn** [comment]
`org-fc-with-point-at-back-heading` is a macro and it seems like in your case it's not loaded as expected.

How did you install org-fc?

**Comment by jaaved** [comment]
Using `use-package`: 
```
;; sudo apt install gawk
(use-package org-fc
  :straight
  (org-fc
   :type git :repo "https://git.sr.ht/~l3kn/org-fc"
   :files (:defaults "awk" "demo.org"))
  :custom
  (org-fc-directories '("~/Dropbox/emacs/org_files"))
  :config
  (require 'org-fc-hydra)
  (global-set-key (kbd "C-c f") 'org-fc-hydra/org-fc-update)

  )
```
@l3kn

**Comment by jaaved** [comment]
@l3kn am I missing something in the config? do I have to load the package with require? I am not able to review the cards after I upgrade emacs from 27 to 28, issue cropped up after the upgrade

**Comment by l3kn** [comment]
There was a similar issue a while ago, with the same macro leading to problems with emacs 28.

I suspected it was caused by files using this macro being loaded before the file that defines it but that was changed with this commit: https://github.com/l3kn/org-fc/commit/43bb7ab15c37b452418e1a9095e01e56d56c5ef8

Maybe you're using an older version of org-fc? I'm not sure how to update packages installed with use-package, is there an entry for `org-fc` when you do a `M-x list-packages`?

**Comment by l3kn** [comment]
Looks like `use-package` doesn't automatically apply updates. If org-fc shows up in `list-packages` you can mark it for an update with `U`, then execute with `x`.

**Comment by jaaved** [comment]
@l3kn  upgrading the org-fc package worked. org-fc is not visible in list-packages, I deleted repo in straight directory and reinstalled with straight again. @l3kn  Thanks.

**Comment by l3kn** [comment]
I'm glad that fixed it. Not sure if there's a better way to update packages installed from git.
