### ISSUE TITLE
"Hidden" fields

### ISSUE THREAD

**Issue by lcabrini** [l3kn/org-fc#66]
When I review Remembering the Kanji in Anki, the "story" is hidden by default. I can click on it if I need it. Is it possible to achieve something similare with org-fc?

**Comment by l3kn** [comment]
There are two ways I can think of:

If you have a card with a "Back" heading, any additional heading will be displayed but not expanded after flipping the card,
so after reviewing a kanji, you read the "story" by expanding that heading:

```
* Word 1                                                                 :fc:
Foo
** Back
Bar
** Story
Baz
```

By default any drawers inside a flashcards will be hidden.
If you add the name of the drawer to the `org-fc-drawer-whitelist`, it will only be collapsed and you could expand it to view the "story":

```
* Word 2                                                                 :fc:
Foo
** Back
Bar

:STORY:
Baz
:END:
```

**Comment by lcabrini** [comment]
I'm not sure alternative (1) would work for me, because I would want the hint to be hidden but displayable on the front. However, the name 'Back' is significant, right? So if I were to add a 'Story' section _before_ the 'Back' one, it should show up on the front card but not be expanded, I suppose. Or at least, I could try to lisp-fu it to dwiw.

Alternative (2) looks like it would work. However, I'd prefer to see the story as part of the card and not meta-data. FWIW, Heisig himself says the story should be on the front and doesn't mention anything about hiding it. So, an third alternative would be to just not try to do fancy stuff just because my brain decided that it would be neat to be able to do.

**Comment by l3kn** [comment]
I just checked and due to how org-fc sets up cards for review, all child headings (not just the "Back") heading will be hidden.

The org manual describes drawers as a way to have information associated with a entry but not always shown,
so their use isn't limited to metadata.

As long as you use a consistent format, you can just start with whatever seems like the best solution for now, then automatically change your cards later, e.g. in combination with a custom card type that doesn't hide the "Story" child heading.

**Comment by l3kn** [comment]
Without further information on this, the using the drawer whitelist should resolve this issue.
